user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;

events {
    worker_connections  1024;
}
stream {
    upstream gitlab_ssh_backend {
        server 172.16.230.15:11022;   # GitLab真实ssh地址端口，如果是docker就填容器IP:22
    }

    server {
        listen 11022;          # 对外暴露的ssh端口，用户git clone用这个端口
        proxy_pass gitlab_ssh_backend;
        proxy_connect_timeout 30s;
        proxy_timeout 3600s;
    }
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    keepalive_timeout  65;

    # 加载所有子域名站点配置
    include /etc/nginx/conf.d/*.conf;
}
